### ISSUE TITLE
panic:  send on closed channel

### ISSUE THREAD

**Issue by l-n-s** [majestrate/XD#22]
```
[NFO] 2017-09-15 11:31:03.697873086 -0400 EDT m=+6950.276936652 Global Speed: Upload: 4.80KB/sec Download: 0.00B/sec
[NFO] 2017-09-15 11:31:13.698236819 -0400 EDT m=+6960.277300315 Global Speed: Upload: 0.00B/sec Download: 0.00B/sec
[WRN] 2017-09-15 11:31:19.82191365 -0400 EDT m=+6966.400977007  write error: write tcp 127.0.0.1:60016->127.0.0.1:7656: write: connection reset by peer
[ERR] 2017-09-15 11:31:19.821961352 -0400 EDT m=+6966.401024918 PeerConn() reader failed: EOF
panic: send on closed channel

goroutine 4140 [running]:
xd/lib/bittorrent/swarm.(*PeerConn).doSend(0xc4202ec000, 0xc424111020)
        /home/user/lab/my_XD/src/xd/lib/bittorrent/swarm/peer.go:83 +0x63
created by xd/lib/bittorrent/swarm.(*PeerConn).Send
        /home/user/lab/my_XD/src/xd/lib/bittorrent/swarm/peer.go:89 +0x49
panic: send on closed channel

rev 6afba87
goroutine 4232 [running]:
xd/lib/bittorrent/swarm.(*PeerConn).doSend(0xc4202ec000, 0xc4216f5ea0)
        /home/user/lab/my_XD/src/xd/lib/bittorrent/swarm/peer.go:83 +0x63
created by xd/lib/bittorrent/swarm.(*PeerConn).Send
        /home/user/lab/my_XD/src/xd/lib/bittorrent/swarm/peer.go:89 +0x49
```

rev 6afba87

**Comment by majestrate** [comment]
git revision please

**Comment by l-n-s** [comment]
I've updated issue after posting lol

rev 6afba87

**Comment by majestrate** [comment]
try commit 2c181f9

**Comment by l-n-s** [comment]
Haven't crash so far, and idk how to reproduce.
